
GET http://localhost:4000/api/inventory-date-expiration

###

GET http://localhost:4000/api/inventory-quantity

###

GET http://localhost:4000/api/inventory

###

GET http://localhost:4000/api/marketing/

###

# POST http://localhost:4000/api/marketing/
# Content-Type: application/json

# {
#     "name": "Sales Promotion",
#     "apply" : 0,
#     "apply_type": [],
#     "apply_product": [],
#     "discount_type": "PERCENT",
#     "value": 10,
#     "status": true,
#     "condition": "DATE",
#     "condition_value": 5
# }


###
GET http://localhost:4000/api/products

###
###
